// <auto-generated />
using System;
using Evidata.Modules.Mcp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Evidata.Modules.Mcp.Migrations
{
    [DbContext(typeof(McpDbContext))]
    [Migration("20260708211945_InitialMcp")]
    partial class InitialMcp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mcp")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Evidata.Modules.Mcp.Domain.McpCitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fragment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("fragment");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid")
                        .HasColumnName("interaction_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_version");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId")
                        .HasDatabaseName("ix_mcp_citations_interaction_id");

                    b.ToTable("mcp_citations", "mcp");
                });

            modelBuilder.Entity("Evidata.Modules.Mcp.Domain.McpInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("question");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_human_review");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("UsedTenantContext")
                        .HasColumnType("boolean")
                        .HasColumnName("used_tenant_context");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_mcp_interactions_tenant_time");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_mcp_interactions_tenant_status");

                    b.ToTable("mcp_interactions", "mcp");
                });

            modelBuilder.Entity("Evidata.Modules.Mcp.Domain.McpCitation", b =>
                {
                    b.HasOne("Evidata.Modules.Mcp.Domain.McpInteraction", null)
                        .WithMany("Citations")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Evidata.Modules.Mcp.Domain.McpInteraction", b =>
                {
                    b.Navigation("Citations");
                });
#pragma warning restore 612, 618
        }
    }
}
