// <auto-generated />
using System;
using Evidata.Modules.ProcessingInventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Evidata.Modules.ProcessingInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProcessingInventoryDbContext))]
    [Migration("20260710174526_AddReviewedAtToProcessingActivity")]
    partial class AddReviewedAtToProcessingActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rat")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Evidata.Modules.ProcessingInventory.Domain.ProcessingActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("Controller")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("controller");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("HasAutomatedDecision")
                        .HasColumnType("boolean")
                        .HasColumnName("has_automated_decision");

                    b.Property<bool>("HasInternationalTransfer")
                        .HasColumnType("boolean")
                        .HasColumnName("has_international_transfer");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("_dataCategories")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_categories")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("_dataSubjects")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_subjects")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("_securityMeasures")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("security_measures")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("_suppliers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("suppliers")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("_systems")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("systems")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_processing_activities_supersedes");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_processing_activities_tenant_name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_processing_activities_tenant_status");

                    b.ToTable("processing_activities", "rat");
                });

            modelBuilder.Entity("Evidata.Modules.ProcessingInventory.Domain.ProcessingActivitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_rat_snapshots_activity_version");

                    b.ToTable("processing_activity_snapshots", "rat");
                });

            modelBuilder.Entity("Evidata.Modules.ProcessingInventory.Domain.ProcessingActivity", b =>
                {
                    b.OwnsOne("Evidata.Modules.ProcessingInventory.Domain.PurposeSection", "Purpose", b1 =>
                        {
                            b1.Property<Guid>("ProcessingActivityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LegalBasis")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("legal_basis");

                            b1.Property<string>("LegalBasisJustification")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("legal_basis_justification");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("purpose_text");

                            b1.HasKey("ProcessingActivityId");

                            b1.ToTable("processing_activities", "rat");

                            b1.WithOwner()
                                .HasForeignKey("ProcessingActivityId");
                        });

                    b.OwnsOne("Evidata.Modules.ProcessingInventory.Domain.RetentionSection", "Retention", b1 =>
                        {
                            b1.Property<Guid>("ProcessingActivityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LegalJustification")
                                .HasColumnType("text")
                                .HasColumnName("retention_legal_justification");

                            b1.Property<string>("PeriodDescription")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("retention_period_description");

                            b1.Property<int?>("RetentionMonths")
                                .HasColumnType("integer")
                                .HasColumnName("retention_months");

                            b1.HasKey("ProcessingActivityId");

                            b1.ToTable("processing_activities", "rat");

                            b1.WithOwner()
                                .HasForeignKey("ProcessingActivityId");
                        });

                    b.OwnsOne("Evidata.Modules.ProcessingInventory.Domain.RiskFlags", "Flags", b1 =>
                        {
                            b1.Property<Guid>("ProcessingActivityId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AutomatedDecision")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_automated_decision");

                            b1.Property<bool>("BiometricData")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_biometric_data");

                            b1.Property<bool>("ChildrenData")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_children_data");

                            b1.Property<bool>("CriticalGapOpen")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_critical_gap_open");

                            b1.Property<bool>("InternationalTransfer")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_international_transfer");

                            b1.Property<bool>("MissingLegalBasisEvidence")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_missing_legal_basis_evidence");

                            b1.Property<bool>("MissingRetention")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_missing_retention");

                            b1.Property<bool>("MissingSecurityMeasures")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_missing_security_measures");

                            b1.Property<bool>("SensitiveData")
                                .HasColumnType("boolean")
                                .HasColumnName("flag_sensitive_data");

                            b1.HasKey("ProcessingActivityId");

                            b1.ToTable("processing_activities", "rat");

                            b1.WithOwner()
                                .HasForeignKey("ProcessingActivityId");
                        });

                    b.Navigation("Flags")
                        .IsRequired();

                    b.Navigation("Purpose");

                    b.Navigation("Retention");
                });
#pragma warning restore 612, 618
        }
    }
}
