// <auto-generated />
using System;
using Evidata.Modules.GapManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Evidata.Modules.GapManagement.Migrations
{
    [DbContext(typeof(GapManagementDbContext))]
    [Migration("20260711171320_SeedGapRules")]
    partial class SeedGapRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gap")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Evidata.Modules.GapManagement.Domain.ComplianceGap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid?>("GapRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("gap_rule_id");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("LegalObligationId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_obligation_id");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("RiskAcceptanceJustification")
                        .HasColumnType("text")
                        .HasColumnName("risk_acceptance_justification");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entity_id");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("GapRuleId")
                        .HasDatabaseName("ix_compliance_gaps_rule");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_compliance_gaps_owner");

                    b.HasIndex("TenantId", "Severity")
                        .HasDatabaseName("ix_compliance_gaps_tenant_severity");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_compliance_gaps_tenant_status");

                    b.HasIndex("TenantId", "SourceModule", "SourceEntityId")
                        .HasDatabaseName("ix_compliance_gaps_source");

                    b.ToTable("compliance_gaps", "gap");
                });

            modelBuilder.Entity("Evidata.Modules.GapManagement.Domain.GapRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BlocksApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("blocks_approval");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImplementationNotes")
                        .HasColumnType("text")
                        .HasColumnName("implementation_notes");

                    b.Property<bool>("IsFullyImplemented")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fully_implemented");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TestFixtureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("test_fixture_name");

                    b.HasKey("Id");

                    b.HasIndex("RuleCode")
                        .HasDatabaseName("ix_gap_rules_code");

                    b.HasIndex("TenantId", "RuleCode")
                        .IsUnique()
                        .HasDatabaseName("ix_gap_rules_tenant_code");

                    b.ToTable("gap_rules", "gap");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000000"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Transferencia de datos sin país destino especificado",
                            ImplementationNotes = "Evalúa si un nodo de transferencia internacional tiene especificado el país destino.",
                            IsFullyImplemented = true,
                            RuleCode = "TRANSFER_WITHOUT_DESTINATION_COUNTRY",
                            Severity = "Critical",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-transfer-no-country"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Transferencia sin receptor identificado",
                            ImplementationNotes = "Verifica que todo nodo de transferencia identifique un receptor o destinatario.",
                            IsFullyImplemented = true,
                            RuleCode = "TRANSFER_WITHOUT_RECEIVER",
                            Severity = "High",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-transfer-no-receiver"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Transferencia internacional sin salvaguarda especificada",
                            ImplementationNotes = "Controla que transferencias internacionales de terceros países cuenten con salvaguarda (Capítulo V RGPD).",
                            IsFullyImplemented = true,
                            RuleCode = "TRANSFER_WITHOUT_SAFEGUARD",
                            Severity = "Critical",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-transfer-no-safeguard"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Transferencia sin evidencia de aprobación o base legal",
                            ImplementationNotes = "Valida que exista evidencia adjunta que apruebe o justifique la transferencia internacional.",
                            IsFullyImplemented = true,
                            RuleCode = "TRANSFER_WITHOUT_BLOCKING_EVIDENCE",
                            Severity = "Critical",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-transfer-no-evidence"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Dato sensible sin revisión de seguridad",
                            ImplementationNotes = "Verifica que categorías de datos sensibles tengan validación de evidencia de tipo Security.",
                            IsFullyImplemented = true,
                            RuleCode = "SENSITIVE_DATA_WITHOUT_SECURITY_REVIEW",
                            Severity = "Critical",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-sensitive-no-security-review"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Base legal no especificada",
                            ImplementationNotes = "Comprueba que todo tratamiento de datos cuente con base legal explícita (consentimiento, contrato, obligación legal, etc.).",
                            IsFullyImplemented = true,
                            RuleCode = "LEGAL_BASIS_MISSING",
                            Severity = "Critical",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-no-legal-basis"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Período de retención no definido",
                            ImplementationNotes = "Requiere especificación de período de retención. Nota: El dominio aún no modela explícitamente 'retention_period_days' en ProcessingActivity.",
                            IsFullyImplemented = false,
                            RuleCode = "RETENTION_UNDEFINED",
                            Severity = "High",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-retention-undefined"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Sin categorías de datos especificadas",
                            ImplementationNotes = "Verifica que al menos una categoría de dato esté vinculada al tratamiento.",
                            IsFullyImplemented = true,
                            RuleCode = "DATA_CATEGORIES_EMPTY",
                            Severity = "High",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-no-data-categories"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Propósito del tratamiento no definido",
                            ImplementationNotes = "Asegura que se especifique claramente el propósito o finalidad del tratamiento de datos.",
                            IsFullyImplemented = true,
                            RuleCode = "PURPOSE_UNDEFINED",
                            Severity = "Critical",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-purpose-undefined"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Sin categorías de interesados especificadas",
                            ImplementationNotes = "Comprueba que al menos una categoría de interesado esté identificada en el tratamiento.",
                            IsFullyImplemented = true,
                            RuleCode = "DATA_SUBJECTS_EMPTY",
                            Severity = "High",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-no-data-subjects"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            BlocksApproval = true,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            Description = "Sistemas sin propietario identificado",
                            ImplementationNotes = "Verifica que todo sistema participante en el tratamiento tenga propietario asignado. Nota: Requiere introspección de nodos que el dominio aún no modeliza completamente.",
                            IsFullyImplemented = false,
                            RuleCode = "SYSTEMS_WITHOUT_OWNER",
                            Severity = "High",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001"),
                            TestFixtureName = "pa-systems-without-owner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
