// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Evidata.Modules.Workflow.Migrations
{
    [DbContext(typeof(Evidata.Modules.Workflow.Infrastructure.Persistence.WorkflowDbContext))]
    [Migration("20260710172650_AddReviewRequirements")]
    partial class AddReviewRequirements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Evidata.Modules.Workflow.Domain.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnName("completed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnName("comments")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnName("reviewer_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnName("requested_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnName("started_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnName("status")
                        .HasColumnType("text");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnName("target_entity_id")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnName("target_entity_type")
                        .HasColumnType("text");

                    b.Property<string>("TargetModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnName("target_module")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_reviews_tenant_status");

                    b.HasIndex("TenantId", "TargetEntityId")
                        .HasDatabaseName("ix_reviews_tenant_entity");

                    b.ToTable("reviews", "workflow");
                });

            modelBuilder.Entity("Evidata.Modules.Workflow.Domain.ReviewRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnName("entity_type")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnName("is_required")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnName("modified_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewType")
                        .HasColumnName("review_type")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_review_requirements_tenant");

                    b.HasIndex("TenantId", "EntityType", "ReviewType")
                        .IsUnique()
                        .HasDatabaseName("ix_review_requirements_tenant_entity_type");

                    b.ToTable("review_requirements", "workflow");
                });

            modelBuilder.Entity("Evidata.Modules.Workflow.Domain.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnName("assigned_to")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnName("completed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnName("due_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnName("started_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnName("status")
                        .HasColumnType("text");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnName("target_entity_id")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnName("target_entity_type")
                        .HasColumnType("text");

                    b.Property<string>("TargetModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnName("target_module")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("uuid");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnName("task_type")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnName("title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AssignedTo")
                        .HasDatabaseName("ix_workflow_tasks_tenant_assignee");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_workflow_tasks_tenant_status");

                    b.HasIndex("TenantId", "TargetEntityId")
                        .HasDatabaseName("ix_workflow_tasks_tenant_entity");

                    b.ToTable("workflow_tasks", "workflow");
                });
#pragma warning restore 612, 618
        }
    }
}
