// <auto-generated />
using System;
using System.Collections.Generic;
using Evidata.Modules.Evidence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Evidata.Modules.Evidence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvidenceDbContext))]
    [Migration("20260708143719_AddEvidencePackJob")]
    partial class AddEvidencePackJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("evidence")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Evidata.Modules.Evidence.Domain.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("blob_path");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("deletion_reason");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sensitivity");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupersedesEvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_evidence_id");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tags");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Sensitivity")
                        .HasDatabaseName("ix_evidences_sensitivity");

                    b.HasIndex("SupersedesEvidenceId")
                        .HasDatabaseName("ix_evidences_supersedes");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_evidences_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_evidences_tenant_status");

                    b.HasIndex("TenantId", "Type")
                        .HasDatabaseName("ix_evidences_tenant_type");

                    b.ToTable("evidences", "evidence");
                });

            modelBuilder.Entity("Evidata.Modules.Evidence.Domain.EvidenceAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accessed_at");

                    b.Property<Guid>("AccessedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("accessed_by");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("SensitivityAtAccess")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sensitivity_at_access");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("AccessedBy")
                        .HasDatabaseName("ix_evidence_access_logs_user");

                    b.HasIndex("EvidenceId")
                        .HasDatabaseName("ix_evidence_access_logs_evidence_id");

                    b.HasIndex("TenantId", "AccessedAt")
                        .HasDatabaseName("ix_evidence_access_logs_tenant_date");

                    b.ToTable("evidence_access_logs", "evidence");
                });

            modelBuilder.Entity("Evidata.Modules.Evidence.Domain.EvidenceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_id");

                    b.Property<Guid>("LinkedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_entity_id");

                    b.Property<string>("LinkedEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("linked_entity_type");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EvidenceId")
                        .HasDatabaseName("ix_evidence_links_tenant_evidence");

                    b.HasIndex("EvidenceId", "LinkedEntityType", "LinkedEntityId", "DeletedAt")
                        .HasDatabaseName("ix_evidence_links_dedup")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("evidence_links", "evidence");
                });

            modelBuilder.Entity("Evidata.Modules.Evidence.Domain.EvidencePackJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("ResultBlobPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("result_blob_path");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<List<Guid>>("_evidenceIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_ids");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_evidence_pack_jobs_expires");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_evidence_pack_jobs_tenant");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_evidence_pack_jobs_tenant_status");

                    b.ToTable("evidence_pack_jobs", "evidence");
                });

            modelBuilder.Entity("Evidata.Modules.Evidence.Domain.EvidenceAccessLog", b =>
                {
                    b.HasOne("Evidata.Modules.Evidence.Domain.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Evidata.Modules.Evidence.Domain.EvidenceLink", b =>
                {
                    b.HasOne("Evidata.Modules.Evidence.Domain.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evidence");
                });
#pragma warning restore 612, 618
        }
    }
}
